#!/bin/bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [[ `uname -s` = "Darwin" ]]; then
    echo "-------------------------------------------"
    echo "Detected OSX, performing software update..."
    echo "-------------------------------------------"
    sudo softwareupdate -i -a
    
    PORT=`port version`
    if [[ PORT != "" ]]; then
        echo "-------------------------------------------"
        echo "Found MacPorts $PORT, updating..."
        echo "-------------------------------------------"
        sudo port selfupdate
        sudo port upgrade outdated
    fi
    
elif [[ `whereis apt-get` != "" ]]; then
    echo "-------------------------------------------"
    echo "Detected APT, performing update & upgrade..."
    echo "-------------------------------------------"
    sudo apt-get update
    sudo apt-get upgrade
else
    echo "Sorry, no supported update mechanism found."
fi

